sudo: required
services:
  - docker

before_install:
  - docker build -t yohaido159/docker-nginx-npm -f Dockerfile.dev .

script:
  - docker run -e CI=true yohaido159/docker-nginx-npm npm run test

language: generic
